<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>dbsync</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DBSync.Core\DBSync.Core.csproj" />
  </ItemGroup>

</Project>
