<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
      <OutputType>WinExe</OutputType>
      <TargetFramework>net10.0</TargetFramework>
      <ImplicitUsings>enable</ImplicitUsings>
      <Nullable>enable</Nullable>
      <ApplicationManifest>app.manifest</ApplicationManifest>
      <UsedAvaloniaProducts></UsedAvaloniaProducts>
      <HotAvalonia>$(IsDebug)</HotAvalonia>
    </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.2" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="12.1.1" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.2" />
    <PackageReference Include="Avalonia.Markup.Xaml.Loader" Version="12.1.2" PrivateAssets="All" Publish="True" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.2" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Easy.Serilog.Core" Version="2026.9.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="HotAvalonia" Version="3.1.4" PrivateAssets="All" Publish="True" />
    <PackageReference Include="SukiUI" Version="7.0.1" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DBSync.Core\DBSync.Core.csproj" />
  </ItemGroup>

</Project>
