<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Easy.Cache.Core" Version="2026.8.18.1" />
    <PackageReference Include="Easy.Serilog.Core" Version="2026.7.2" />
    <PackageReference Include="Easy.SqlSugar.Core" Version="2026.6.25.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
  </ItemGroup>

</Project>
